---
development:
  dialect: postgres
  database: nikkidb
  user: postgres
  password: postgres
  host: postgres
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/nikki_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/nikki_production?sslmode=disable"}}
